### ISSUE TITLE
0.6.6 32bit test hang

### ISSUE THREAD

**Issue by AdrianBunk** [GaloisInc/libBF-hs#26]
@RyanGlScott The test you added in #24 hangs on 32bit: https://buildd.debian.org/status/logs.php?pkg=haskell-libbf&ver=0.6.6-1

There is a warning during the build:
```
src/LibBF/Mutable.hsc:588:22: warning: [-Woverflowed-literals]
    Literal 2147483648 is out of the Int32 range -2147483648..2147483647
    Suggested fix:
      Perhaps you intended to use NegativeLiterals
      If you are trying to write a large negative literal
    |
588 |                 e > #{const BF_EXP_ZERO} then Just (fromIntegral e)
    |                      ^^^^^^^^^^
```

The warning might or might not be related to the test hang, this issue is primarily about the test hang.

**Comment by RyanGlScott** [comment]
Sorry about that! I haven't had an opportunity to extensively test `libBF-hs` on 32-bit architectures, primarily because I don't own a 32-bit machine. (I suppose I could try this on a 32-bit Docker image, unless you have an easier way to test this.)

For what it's worth, I suspect that the issue may lie in the upstream `libbf` C library, since `BF_EXP_ZERO` evaluates to a number that cannot be represented in a 32-bit integer. I would have to see if someone has patched the library to make it work as expected on 32-bit platforms. (There is a partially patched version of `libbf` in [this repo](https://github.com/rurban/libbf), including a 32-bit–specific commit [here](https://github.com/rurban/libbf/commit/1fc8243d151541dea80b45a2052fa03b423b6d8d), so that might be a good place to look.)

**Comment by Bodigrim** [comment]
> (I suppose I could try this on a 32-bit Docker image, unless you have an easier way to test this.)

You can setup GHA to run 32-bit tests: https://github.com/haskell/text/blob/master/.github/workflows/i386.yml

**Comment by RyanGlScott** [comment]
Yes, good point. For that matter, we should set up _any_ kind of CI (see https://github.com/GaloisInc/libBF-hs/issues/25).

**Comment by RyanGlScott** [comment]
I'm able to confirm the test suite hang in #31. (See [this](https://github.com/GaloisInc/libBF-hs/actions/runs/7033220240/job/19138561419?pr=31) failing CI job.) Curiously, the CI didn't observe the overflow warning reported in https://github.com/GaloisInc/libBF-hs/issues/26#issue-1955905547, so I'm not sure what is going on there. Note that `BF_EXP_ZERO` is defined to be the smallest 32-bit integer value:

```c
#if LIMB_BITS == 64
... 
#else
...
#define BF_RAW_EXP_MIN INT32_MIN
...
#endif

...
#define BF_EXP_ZERO BF_RAW_EXP_MIN
```

And if I look at the results of running `hsc2hs` on `LibBF.Mutable`, they appear reasonable:

```hs
-- | Get the exponent of the number.
-- Returns 'Nothing' for inifinity, zero and NaN.
getExp :: BF -> IO (Maybe Int64)
getExp = bf1 (\ptr ->
  do e <- (\hsc_ptr -> peekByteOff hsc_ptr 8) ptr
{-# LINE 589 "src/LibBF/Mutable.hsc" #-}
     pure $! if (e :: SLimbT) < 2147483646 &&
{-# LINE 590 "src/LibBF/Mutable.hsc" #-}
                e > -2147483648 then Just (fromIntegral e)
{-# LINE 591 "src/LibBF/Mutable.hsc" #-}
                                else Nothing)
```

Here, `-2147483648` is substituted for `BF_EXP_ZERO`, and that is indeed the smallest possible 32-bit integer value. Perhaps there is something else amiss, but I'm less certain that `BF_EXP_ZERO` is the culprit.

Besides that, I don't have many other leads to go on at the moment. [This `libbf` fork](https://github.com/rurban/libbf) contains a commit [here](https://github.com/rurban/libbf/commit/1fc8243d151541dea80b45a2052fa03b423b6d8d) which looks promising, but I tried cherry-picking that commit, and it didn't fix the test suite hang. Unfortunately, I've ran out of time to look at this for the moment, so if anyone here has expertise in debugging 32-bit–specific issues, your advice would be greatly appreciated. (The CI template in #31 might prove useful in debugging this further.)

**Comment by RyanGlScott** [comment]
Ah, I see what is going on here. In the implementation of `toRep` (a key function used throughout the Haskell bindings), we see:

https://github.com/GaloisInc/libBF-hs/blob/99e603658a70feac1825e7604424b1c914b7fe27/src/LibBF/Mutable.hsc#L600-L608

When the `BigFloat` argument is, say, `bfPosZero`, then the underlying `bf_t`'s `expn` value will be `BF_EXP_ZERO`, which should be `-2147483648` on 32-bit architectures. But after inserting some debug printing after the call to `#{peek bf_t, expn} ptr`, it turns out `e` (the Haskell equivalent of the `expn` value) is `-2147483648`, not `2147483648`! The reason this happens is because elsewhere in the implementation of `toRep`, we use `e` as the second argument to `Num`:

https://github.com/GaloisInc/libBF-hs/blob/99e603658a70feac1825e7604424b1c914b7fe27/src/LibBF/Mutable.hsc#L623

But the second argument of `Num` is an `Int64`. Therefore, the `#{peek bf_t, expn} ptr` call above will read `expn` at type `Int64`. This is very dubious, because the underlying type of `expn` is `slimb_t`. On 32-bit architectures, `slimb_t` is `Int32`, not `Int64`! This means that `peek` reads a completely wrong value, and the code that follows goes into an infinite loop as a result.

The following patch suffices to fix the issue:

```diff
diff --git a/src/LibBF/Mutable.hsc b/src/LibBF/Mutable.hsc
index f9810d8..c1a19e1 100644
--- a/src/LibBF/Mutable.hsc
+++ b/src/LibBF/Mutable.hsc
@@ -602,7 +602,7 @@ toRep :: BF -> IO BFRep
 toRep = bf1 (\ptr ->
   do s <- #{peek bf_t, sign} ptr
      let sgn = if asBool s then Neg else Pos
-     e <- #{peek bf_t, expn} ptr
+     e <- #{peek bf_t, expn} ptr :: IO SLimbT
      if | e == #{const BF_EXP_NAN}  -> pure BFNaN
         | e == #{const BF_EXP_INF}  -> pure (BFRep sgn Inf)
         | e == #{const BF_EXP_ZERO} -> pure (BFRep sgn Zero)
@@ -620,7 +620,7 @@ toRep = bf1 (\ptr ->
            let bias = 64 * fromIntegral len
                norm bs bi
                  | even bs    = norm (bs `shiftR` 1) (bi - 1)
-                 | otherwise  = BFRep sgn (Num bs (e - bi))
+                 | otherwise  = BFRep sgn (Num bs (fromIntegral e - bi))
 
            pure (norm base bias) -- (BFRep sgn (Num base (e - bias)))
   )
```

I audited every other use of `#peek` in the code, and as far as I can tell, this was the only spot that `peek`ed at an incorrect type.
