### ISSUE TITLE
[Feature request] Data instance for BigFloat

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/libBF-hs#28]
Would be nice to have a `Data` instance for `BigFloat`: I've a large data-type that has `BigFloat`'s stored deep in the hierarchy that I'd like to make an instance of `Data` for some generic programming. Alas, I can't define it by myself (I think, correct me if I'm wrong), since the constructors are not exported and GHC can't deriving `Data` unless all the constructors are visible.

Is there a way to achieve this directly from my code? If not, would it be possible for you to add the instance so it's available automatically from the library?

**Comment by RyanGlScott** [comment]
I wouldn't mind adding a `Data` instance for `BigFloat`, but since `BigFloat` is an abstract data type, I think we'd want to implement `gfoldl` in a way such that it doesn't allow you to retrieve the underlying `ForeignPtr`:

```hs
instance Data BigFloat where
  gfoldl _ z = z
  ...
```

Would this be acceptable for your use case? This likely wouldn't impact standard, `uniplate`-style uses of `Data`, but let me know if this would be an issue.

**Comment by LeventErkok** [comment]
Uniplate is exactly my use case, so I think this would work just fine. Would be great to have this released soon if at all possible. Thanks!

**Comment by RyanGlScott** [comment]
I've added such an instance in https://github.com/GaloisInc/libBF-hs/pull/30. Could you check if this works for your needs?

**Comment by LeventErkok** [comment]
Great! Yes, this works just fine for my purposes. A release would be much appreciated.

**Comment by RyanGlScott** [comment]
I've uploaded [`libBF-0.6.7`](https://hackage.haskell.org/package/libBF-0.6.7) to Hackage with these changes.

**Comment by LeventErkok** [comment]
Fantastic! Thanks for the quick turnaround.
